#!/bin/sh
# Copyright (C) 2010-2015 David Bond, All Rights Reserved

DIR=${1:-src/}

OVERHEAD=2.4
SALARY=100000

HFILES=`find $DIR -type f -name "*.hpp"`
CFILES=`find $DIR -type f -name "*.cpp"`
HLC=`wc -l $HFILES 2> /dev/null | tail -1 | awk '{print $1}'`
CLC=`wc -l $CFILES 2> /dev/null | tail -1 | awk '{print $1}'`
TLC=`expr $HLC + $CLC`

SLOCCOUNT=`sloccount --personcost $SALARY --overhead $OVERHEAD src/`
PSLOC=`echo "$SLOCCOUNT" |grep "Total Physical Source Lines of Code (SLOC)" \
  | cut -f2 -d'='| sed 's/,//g'| sed 's/)//g'`
COST=`echo "$SLOCCOUNT" |grep "Total Estimated Cost to Develop" \
  | cut -f2 -d'=' | cut -f2 -d'$'| sed 's/,//g' | sed 's/ //g'`
MONTHS=`echo "$SLOCCOUNT" |grep "Development Effort Estimate," \
  | cut -f2 -d'=' | cut -f2 -d'('| sed 's/)//g'`

UCC -dir $DIR  "*.cpp" "*.h" "*.c" "*.hpp" &> /dev/null
LSLOC=`cat C_CPP_outfile.csv |grep Logical |grep -v SLOC |grep -v Total \
  |awk -F"," '{print $8}'`
[ -f C_CPP_outfile.csv ] && rm C_CPP_outfile.csv
[ -f outfile_*.csv ] && rm outfile_*.csv
[ -f Duplicate*.csv ] && rm Duplicate*.csv

if [ -z $LSLOC ] ; then
  LSLOC=$PSLOC
fi

function echo_line {
  echo "------------------------------------------------------------------------------"
}

echo "Assumptions"
echo_line
echo "Overhead: ${OVERHEAD} times"
echo "Salary: \$$SALARY"

echo -e "\nLine Counts"
echo_line
echo "Header File Line Count $HLC"
echo "Code File Line Count $CLC"
echo "Line Count $TLC"
echo "COCOMO PSLOC: $PSLOC"
echo "COCOMO II LSLOC: $LSLOC"

echo -e "\nCOCOMO Estimation"
echo_line
echo "Person Months: $MONTHS"
echo "Cost: \$`echo "$COST/$OVERHEAD" | bc`"
echo "Cost & Overhead: \$$COST"

echo -e "\nCOCOMO II Estimation"
echo_line
echo -e "\nNominal Team & Environment"
echo "--------------------"
mspe --sloc $LSLOC --overhead $OVERHEAD --salary $SALARY --team nominal

echo -e "\nExpert Team & Environment"
echo "--------------------"
mspe --sloc $LSLOC --overhead $OVERHEAD --salary $SALARY --team expert
